CRUD in-memory db task/App2/App/Models/ProfilesViewModel.cs
using App.Settings;
using System;
using System.ComponentModel.DataAnnotations;

namespace App.Models
{
    public class ProfilesViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "ФИО")]
        [StringLength(100, ErrorMessage = "Длина строки должна быть до 100 символов")]
        public string Fullname { get; set; }

        [Required]
        [Display(Name = "Дата рождения")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        [CustomDate(-65, -18, ErrorMessage = "Значение должно быть от (*текущая дата* - 65 лет) до (*текущая дата* - 18 лет)")]
        public string Date { get; set; }

        [Required]
        [Display(Name = "Email")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Некорректный адрес")]
        [DataType(DataType.EmailAddress)]
        [StringLength(50, ErrorMessage = "Длина строки должна быть до 50 символов")]
        public string Email { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Номер телефона")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(15, ErrorMessage = "Длина строки должна быть до 15 символов")]
        public string Phone { get; set; }

        public WorkersViewModel WorkersViewModel { get; set; }

    }
}

CRUD in-memory db task/App2/App/Models/WorkersViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace App.Models
{
    public class WorkersViewModel
    {
        
        public  int Id { get; set; }

        [Required]
        [Display(Name = "Должность")]
        [StringLength(100, ErrorMessage = "Длина строки должна быть до 100 символов")]
        public string Position { get; set; }

        [Required]
        [Display(Name = "Подразделение")]
        [StringLength(150, ErrorMessage = "Длина строки должна быть до 150 символов")]
        public string Subdivision { get; set; }

        [Required]
        [Display(Name = "Оклад")]
        [Range(1, 200000, ErrorMessage = "Диапозон значений от 1 до 200000")]
        public int Salary { get; set; }
        public virtual ProfilesViewModel Profile { get; set; }

    }
}

CRUD in-memory db task/App2/App/Pages/Index.cshtml.cs
using App.Models;
using ApplicationCore.Entities.Main;
using ApplicationCore.Interfaces.Base;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Infrastructure.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace App.Pages
{
    public class IndexModel : PageModel
    {
        public IEnumerable<WorkersViewModel> ongetWorkers;

        private readonly IEFRepository<Worker> WorkerRepository;

        [BindProperty]
        public Worker Worker { get; set; }

        public IndexModel(IEFRepository<Worker> workerRepository)
        {
            WorkerRepository = workerRepository;
        }

        public async void OnGet(int OrderId = 0)
        {
            //  DTO(data transfer object) model
            //  получение списка воркеров
            var getWorkers = await WorkerRepository.ListAsync();

            if (OrderId == 1) getWorkers = getWorkers.OrderByDescending(x => x.Id);
            // mapping
            // преобразование списка воркеров в список вьюмоделей воркеров и профилей
            ongetWorkers = getWorkers.Adapt<IEnumerable<WorkersViewModel>>();
        }


        public async Task<IActionResult> OnPostAdd()
        {
            if (ModelState.IsValid)
            {
                await WorkerRepository.AddAsync(Worker);
                return RedirectToPage("Index");
            }
            else
            {
                return RedirectToAction("OnPostAdd",Worker);
            }
        }

        public async Task<IActionResult> OnGetDelete(int id)
        {
            await WorkerRepository.DeleteAsync(id);
            return RedirectToPage("Index");
        }

    }
}

CRUD in-memory db task/App2/App/Pages/Update.cshtml.cs
using App.Models;
using ApplicationCore.Entities.Interfaces;
using ApplicationCore.Entities.Main;
using ApplicationCore.Interfaces.Base;
using ApplicationCore.Services;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace App.Pages
{
    public class UpdateModel : PageModel
    {
        private readonly IEFRepository<Worker> WorkerRepository;
		private readonly IWorkerService WorkerService;


        [BindProperty]
        public WorkersViewModel Worker { get; set; }

        public UpdateModel(IEFRepository<Worker> workerRepository,
                           IWorkerService workerService)
        {
            WorkerRepository = workerRepository;
			WorkerService = workerService;
        }

        public async Task OnGet(int id)
        {
            Worker currentWorker = await WorkerRepository.FindAsync(id);
            Worker = currentWorker.Adapt<WorkersViewModel>();

        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var newModel = Worker.Adapt<Worker>();
                await WorkerService.UpdateAsync(newModel);
                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

CRUD in-memory db task/App2/App/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@{
    var listItem = new List<SelectListItem>();
    listItem.Add(new SelectListItem
            {
                Text = "По возрастанию",
                Value = "0"
            });
    listItem.Add(new SelectListItem
            {
                Text = "По убыванию",
                Value = "1"
            });
}


<br />
<div class="container" row p-0 m-0>
    <div class="col-12">
        <h2 class="text-info ml-2">Список сотрудников</h2>

        <form asp-page="Index" method="get" class="row mb-2 ml-2">
            @Html.DropDownList("OrderId", listItem, "", new { style = "width: 70%", @class = "form-control" })
            <button type="submit" class="btn btn-info ml-3">Обновить</button>
        </form>
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>ФИО</th>
                    <th>Дата рождения</th>
                    <th>Подразделение</th>
                    <th>Должность</th>
                    <th>Оклад</th>
                    <th>Email</th>
                    <th>Телефон</th>
                    <th></th>
                    <th><a class="btn btn-info form-control text-white" data-toggle="modal" data-target="#createModal" data-backdrop="static">Создать</a></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var worker in Model.ongetWorkers)
                {
                    <tr>
                        <th scope="row">@worker.Id</th>
                        <td>@worker.Profile.Fullname</td>
                        <td>@worker.Profile.Date</td>
                        <td>@worker.Subdivision</td>
                        <td>@worker.Position</td>
                        <td>@worker.Salary</td>
                        <td>@worker.Profile.Email</td>
                        <td>@worker.Profile.Phone</td>
                        <td><a class="btn btn-success form-control text-white" asp-page="Update" asp-route-id="@worker.Id">Редактировать</a></td>
                        <td>
                            <a class="btn btn-danger form-control text-white" asp-page="Index" asp-route-id="@worker.Id" asp-page-handler="Delete"
                           onclick="return confirm('Вы действительно хотите удалить данного сотрудника?')">Удалить</a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<!--CreateModal-->
<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createModalLabel">Добавление нового сотрудника</h5>
                <button class="btn-close btn-dark" data-dismiss="modal" aria-label="close"></button>
            </div>
            <div class="modal-body">
                <form asp-page="Index" method="post">
                    <table class="table">
                        <!--Fullname-->
                        <tr>
                            <th>
                                <label asp-for="Worker.Profile.Fullname">ФИО</label>
                            </th>
                            <td>
                                <input asp-for="Worker.Profile.Fullname" class="form-control" />
                                <span asp-validation-for="Worker.Profile.Fullname" class="text-danger"></span>
                            </td>
                        </tr>
                        <!--Date-->
                        <tr>
                            <th><label asp-for="Worker.Profile.Date">Дата рождения</label></th>
                            <td>
                                <input asp-for="Worker.Profile.Date" type="text" class="form-control" />
                                <span asp-validation-for="Worker.Profile.Date" class="text-danger"></span>
                            </td>


                        </tr>
                        <!--Subdivision-->
                        <tr>
                            <th>
                                <label asp-for="Worker.Subdivision">Подразделение</label>
                            </th>
                            <td>
                                <input asp-for="Worker.Subdivision" class="form-control" />
                                <span asp-validation-for="Worker.Subdivision" class="text-danger"></span>
                            </td>
                        </tr>
                        <!--Position-->
                        <tr>

                            <th>
                                <label asp-for="Worker.Position">Должность</label>
                            </th>
                            <td>
                                <input asp-for="Worker.Position" class="form-control" />
                                <span asp-validation-for="Worker.Position" class="text-danger"></span>
                            </td>
                        </tr>
                        <!--Salary-->
                        <tr>
                            <th>
                                <label asp-for="Worker.Salary">Оклад</label>
                            </th>
                            <td>
                                <input asp-for="Worker.Salary" class="form-control" />
                                <span asp-validation-for="Worker.Salary" class="text-danger"></span>
                            </td>
                        </tr>
                        <!--Email-->
                        <tr>
                            <th>
                                <label asp-for="Worker.Profile.Email">Email</label>
                            </th>
                            <td>
                                <input asp-for="Worker.Profile.Email" class="form-control" />
                                <span asp-validation-for="Worker.Profile.Email" class="text-danger"></span>
                            </td>
                        </tr>
                        <!--Phone-->
                        <tr>
                            <th>
                                <label asp-for="Worker.Profile.Phone">Телефон</label>
                            </th>
                            <td>
                                <input asp-for="Worker.Profile.Phone" class="form-control" />
                                <span asp-validation-for="Worker.Profile.Phone" class="text-danger"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td><input class="btn btn-outline-success" asp-page-handler="Add" type="submit" value="Сохранить" /></td>
                            <td><button class="btn btn-outline-danger" data-dismiss="modal">Закрыть</button></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
<!--CreateModal-->

CRUD in-memory db task/App2/App/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:whitesmoke">
    <header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

CRUD in-memory db task/App2/App/Pages/Update.cshtml
@page
@model App.Pages.UpdateModel
@{
}
<form asp-page="Update" method="post" class="row mt-4">
    <br />
    <br />
    <h2>Редактирование данных о сотруднике</h2>
    <br />

    <input type="hidden" asp-for="Worker.Id" name="Worker.Id" />
    <input type="hidden" asp-for="Worker.Profile.Id" name="Worker.Profile.Id" />

    <table class="table">
        <!--Fullname-->
        <tr>
            <th>
                <label asp-for="Worker.Profile.Fullname">ФИО</label>
            </th>
            <td>
                <input asp-for="Worker.Profile.Fullname" class="form-control" />
                <span asp-validation-for="Worker.Profile.Fullname" class="text-danger"></span>
            </td>
        </tr>
        <!--Date-->
        <tr>
            <th><label asp-for="Worker.Profile.Date">Дата рождения</label></th>
            <td><input asp-for="Worker.Profile.Date" type="text" class="form-control" />
            <span asp-validation-for="Worker.Profile.Date" class="text-danger"></span></td>
            

        </tr>
        <!--Subdivision-->
        <tr>
            <th>
                <label asp-for="Worker.Subdivision">Подразделение</label>
            </th>
            <td>
                <input asp-for="Worker.Subdivision" class="form-control" />
                <span asp-validation-for="Worker.Subdivision" class="text-danger"></span>
            </td>
        </tr>
        <!--Position-->
        <tr>
            
            <th>
                <label asp-for="Worker.Position">Должность</label>
            </th>
            <td>
                <input asp-for="Worker.Position" class="form-control" />
                <span asp-validation-for="Worker.Position" class="text-danger"></span>
            </td>
        </tr>
        <!--Salary-->
        <tr>
            <th>
                <label asp-for="Worker.Salary">Оклад</label>
            </th>
            <td>
                <input asp-for="Worker.Salary" class="form-control" />
                <span asp-validation-for="Worker.Salary" class="text-danger"></span>
            </td>
        </tr>
        <!--Email-->
        <tr>
            <th>
                <label asp-for="Worker.Profile.Email">Email</label>
            </th>
            <td>
                <input asp-for="Worker.Profile.Email" class="form-control" />
                <span asp-validation-for="Worker.Profile.Email" class="text-danger"></span>
            </td>
        </tr>
        <!--Phone-->
        <tr>
            <th>
                <label asp-for="Worker.Profile.Phone">Телефон</label>
            </th>
            <td>
                <input asp-for="Worker.Profile.Phone" class="form-control" />
                <span asp-validation-for="Worker.Profile.Phone" class="text-danger"></span>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><input class="btn btn-outline-success" type="submit" value="Сохранить" /></td>
        </tr>
    </table>
</form>